// USERS

export const FIND_ALL_USER = 'FIND_ALL_USER';
export const FIND_ALL_USER_SUCCESS = 'FIND_ALL_USER_SUCCESS';
export const FIND_ALL_USER_FAILURE = 'FIND_ALL_USER_FAILURE';
export const FIND_USER_BY_ID = 'FIND_USER_BY_ID';
export const FIND_USER_BY_ID_SUCCESS = 'FIND_USER_BY_ID_SUCCESS';
export const FIND_USER_BY_ID_FAILURE = 'FIND_USER_BY_ID_FAILURE';
export const REMOVE_USER_BY_ID = 'REMOVE_USER_BY_ID';
export const REMOVE_USER_BY_ID_SUCCESS = 'REMOVE_USER_BY_ID_SUCCESS';
export const REMOVE_USER_BY_ID_FAILURE = 'REMOVE_USER_BY_ID_FAILURE';
export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE = 'SAVE_USER_FAILURE';

// EDUCATION:

export const FIND_ALL_EDUCATION = 'FIND_ALL_EDUCATION';
export const FIND_ALL_EDUCATION_SUCCESS = 'FIND_ALL_EDUCATION_SUCCESS';
export const FIND_ALL_EDUCATION_FAILURE = 'FIND_ALL_EDUCATION_FAILURE';
export const FIND_EDUCATION_BY_ID = 'FIND_EDUCATION_BY_ID';
export const FIND_EDUCATION_BY_ID_SUCCESS = 'FIND_EDUCATION_BY_ID_SUCCESS';
export const FIND_EDUCATION_BY_ID_FAILURE = 'FIND_EDUCATION_BY_ID_FAILURE';
export const REMOVE_EDUCATION_BY_ID = 'REMOVE_EDUCATION_BY_ID';
export const REMOVE_EDUCATION_BY_ID_SUCCESS = 'REMOVE_EDUCATION_BY_ID_SUCCESS';
export const REMOVE_EDUCATION_BY_ID_FAILURE = 'REMOVE_EDUCATION_BY_ID_FAILURE';
export const SAVE_EDUCATION = 'SAVE_EDUCATION';
export const SAVE_EDUCATION_SUCCESS = 'SAVE_EDUCATION_SUCCESS';
export const SAVE_EDUCATION_FAILURE = 'SAVE_EDUCATION_FAILURE';

// EXPERIENCE

export const FIND_ALL_EXPERIENCE = 'FIND_ALL_EXPERIENCE';
export const FIND_ALL_EXPERIENCE_SUCCESS = 'FIND_ALL_EXPERIENCE_SUCCESS';
export const FIND_ALL_EXPERIENCE_FAILURE = 'FIND_ALL_EXPERIENCE_FAILURE';
export const FIND_EXPERIENCE_BY_ID = 'FIND_EXPERIENCE_BY_ID';
export const FIND_EXPERIENCE_BY_ID_SUCCESS = 'FIND_EXPERIENCE_BY_ID_SUCCESS';
export const FIND_EXPERIENCE_BY_ID_FAILURE = 'FIND_EXPERIENCE_BY_ID_FAILURE';
export const REMOVE_EXPERIENCE_BY_ID = 'REMOVE_EXPERIENCE_BY_ID';
export const REMOVE_EXPERIENCE_BY_ID_SUCCESS = 'REMOVE_EXPERIENCE_BY_ID_SUCCESS';
export const REMOVE_EXPERIENCE_BY_ID_FAILURE = 'REMOVE_EXPERIENCE_BY_ID_FAILURE';
export const SAVE_EXPERIENCE = 'SAVE_EXPERIENCE';
export const SAVE_EXPERIENCE_SUCCESS = 'SAVE_EXPERIENCE_SUCCESS';
export const SAVE_EXPERIENCE_FAILURE = 'SAVE_EXPERIENCE_FAILURE';